services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  api:
    build: .
    restart: always
    entrypoint: ["./wait-for-it.sh", "db:3306", "--", "python", "run.py"]
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    command: python run.py

volumes:
  db_data:
